# Generated by Django 5.0.6 on 2025-08-09 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('skills', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PointsPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='package name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='package name (Arabic)')),
                ('points', models.PositiveIntegerField(verbose_name='points')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='price')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='currency')),
                ('discount_percentage', models.PositiveIntegerField(default=0, verbose_name='discount percentage')),
                ('is_popular', models.BooleanField(default=False, verbose_name='is popular')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Points Package',
                'verbose_name_plural': 'Points Packages',
                'ordering': ['points'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('points_amount', models.PositiveIntegerField(verbose_name='points amount')),
                ('platform_fee', models.PositiveIntegerField(verbose_name='platform fee')),
                ('total_points', models.PositiveIntegerField(verbose_name='total points')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('disputed', 'Disputed')], default='pending', max_length=20, verbose_name='status')),
                ('requirements', models.TextField(blank=True, verbose_name='requirements')),
                ('delivery_notes', models.TextField(blank=True, verbose_name='delivery notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='accepted at')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='started at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('expected_delivery', models.DateTimeField(blank=True, null=True, verbose_name='expected delivery')),
                ('actual_delivery', models.DateTimeField(blank=True, null=True, verbose_name='actual delivery')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_buyer', to=settings.AUTH_USER_MODEL)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders_as_seller', to=settings.AUTH_USER_MODEL)),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_orders', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PointsTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('earned', 'Earned'), ('spent', 'Spent'), ('refund', 'Refund'), ('bonus', 'Bonus'), ('penalty', 'Penalty')], max_length=20, verbose_name='transaction type')),
                ('amount', models.IntegerField(verbose_name='amount')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='status')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='description')),
                ('reference_id', models.CharField(blank=True, max_length=100, verbose_name='reference ID')),
                ('payment_id', models.CharField(blank=True, max_length=100, verbose_name='payment ID')),
                ('balance_before', models.PositiveIntegerField(verbose_name='balance before')),
                ('balance_after', models.PositiveIntegerField(verbose_name='balance after')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='points.order')),
                ('skill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='skills.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='points_transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Points Transaction',
                'verbose_name_plural': 'Points Transactions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['buyer', 'status'], name='points_orde_buyer_i_daf060_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['seller', 'status'], name='points_orde_seller__7fc803_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='points_orde_status_db15a2_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['created_at'], name='points_orde_created_e106a2_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['user', 'transaction_type'], name='points_poin_user_id_47b79d_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['status'], name='points_poin_status_98ce44_idx'),
        ),
        migrations.AddIndex(
            model_name='pointstransaction',
            index=models.Index(fields=['created_at'], name='points_poin_created_d44204_idx'),
        ),
    ]
