# Generated by Django 5.0.6 on 2025-08-09 17:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('points', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='amount')),
                ('currency', models.CharField(default='EGP', max_length=3, verbose_name='currency')),
                ('payment_method', models.CharField(choices=[('stripe', 'Stripe'), ('paypal', 'PayPal'), ('paymob', 'Paymob'), ('vodafone_cash', 'Vodafone Cash'), ('etisalat_cash', 'Etisalat Cash'), ('orange_cash', 'Orange Cash')], max_length=20, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='status')),
                ('external_payment_id', models.CharField(blank=True, max_length=200, verbose_name='external payment ID')),
                ('external_reference', models.CharField(blank=True, max_length=200, verbose_name='external reference')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='metadata')),
                ('failure_reason', models.TextField(blank=True, verbose_name='failure reason')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='completed at')),
                ('points_package', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='points.pointspackage')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-created_at'],
            },
        ),
    ]
