services:
  # قاعدة البيانات PostgreSQL
  db:
    image: postgres:15
    container_name: skillswap_db
    environment:
      POSTGRES_DB: skillswap
      POSTGRES_USER: skillswap
      POSTGRES_PASSWORD: skillswap123
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - skillswap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillswap -d skillswap"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis للتخزين المؤقت والرسائل
  redis:
    image: redis:7-alpine
    container_name: skillswap_redis
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - skillswap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # تطبيق Django الرئيسي
  web:
    build: .
    container_name: skillswap_web
    command: >
      sh -c "
      python manage.py collectstatic --noinput &&
      python manage.py makemigrations &&
      python manage.py migrate &&
      python manage.py shell -c \"
      from django.contrib.auth import get_user_model;
      User = get_user_model();
      if not User.objects.filter(username='admin').exists():
          User.objects.create_superuser('admin', 'admin@skillswap.com', 'admin123');
          print('Superuser created successfully');
      else:
          print('Superuser already exists');
      \" &&
      python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
      - CORS_ALLOWED_ORIGINS=http://localhost:3000,http://127.0.0.1:3000
    networks:
      - skillswap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Worker للمهام الخلفية
  celery:
    build: .
    container_name: skillswap_celery
    command: celery -A skillswap worker --loglevel=info
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    networks:
      - skillswap-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "celery", "-A", "skillswap", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Celery Beat للمهام المجدولة
  celery-beat:
    build: .
    container_name: skillswap_celery_beat
    command: celery -A skillswap beat --loglevel=info
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    depends_on:
      - db
      - redis
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    networks:
      - skillswap-network
    restart: unless-stopped

  # Flower لمراقبة Celery
  flower:
    build: .
    container_name: skillswap_flower
    command: >
      sh -c "
      pip install flower &&
      celery -A skillswap flower --port=5555
      "
    ports:
      - "5555:5555"
    depends_on:
      - redis
      - celery
    environment:
      - DEBUG=True
      - SECRET_KEY=django-insecure-dev-key-change-in-production
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
      - REDIS_URL=redis://redis:6379/1
    networks:
      - skillswap-network
    restart: unless-stopped

# الشبكات
networks:
  skillswap-network:
    driver: bridge

# التخزين المستمر
volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:
