services:
  db:
    image: postgres:15
    container_name: skillswap_db
    environment:
      POSTGRES_DB: skillswap
      POSTGRES_USER: skillswap
      POSTGRES_PASSWORD: skillswap123
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"
    networks:
      - skillswap-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U skillswap -d skillswap"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: skillswap_redis
    ports:
      - "6380:6379"
    networks:
      - skillswap-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build: .
    container_name: skillswap_web
    command: >
      sh -c "
        python manage.py collectstatic --noinput &&
        python manage.py makemigrations &&
        python manage.py migrate &&
        python scripts/create_superuser.py &&
        python manage.py runserver 0.0.0.0:8000
      "
    volumes:
      - .:/app
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - skillswap-network
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/admin/"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery:
    build: .
    container_name: skillswap_celery
    command: celery -A skillswap worker --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - skillswap-network
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - REDIS_URL=redis://redis:6379/0
    healthcheck:
      test: ["CMD", "celery", "-A", "skillswap", "inspect", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  celery-beat:
    build: .
    container_name: skillswap_celery_beat
    command: celery -A skillswap beat --loglevel=info
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    networks:
      - skillswap-network
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - REDIS_URL=redis://redis:6379/0

  flower:
    build: .
    container_name: skillswap_flower
    command: celery -A skillswap flower --port=5555
    volumes:
      - .:/app
    ports:
      - "5555:5555"
    depends_on:
      - redis
    networks:
      - skillswap-network
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://skillswap:skillswap123@db:5432/skillswap
      - REDIS_URL=redis://redis:6379/0

volumes:
  postgres_data:
  static_volume:
  media_volume:

networks:
  skillswap-network:
    driver: bridge

