# Generated by Django 5.0.6 on 2025-08-09 17:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('name_ar', models.CharField(blank=True, max_length=100, verbose_name='name (Arabic)')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('icon', models.CharField(blank=True, max_length=50, verbose_name='icon')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('title_ar', models.CharField(blank=True, max_length=200, verbose_name='title (Arabic)')),
                ('description', models.TextField(verbose_name='description')),
                ('description_ar', models.TextField(blank=True, verbose_name='description (Arabic)')),
                ('points_required', models.PositiveIntegerField(verbose_name='points required')),
                ('estimated_duration', models.CharField(max_length=100, verbose_name='estimated duration')),
                ('language', models.CharField(choices=[('en', 'English'), ('ar', 'Arabic'), ('both', 'Both')], default='en', max_length=10, verbose_name='language')),
                ('difficulty', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='beginner', max_length=20, verbose_name='difficulty')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='skills/thumbnails/', verbose_name='thumbnail')),
                ('video_intro', models.URLField(blank=True, verbose_name='video introduction')),
                ('status', models.CharField(choices=[('active', 'Active'), ('paused', 'Paused'), ('completed', 'Completed')], default='active', max_length=20, verbose_name='status')),
                ('is_featured', models.BooleanField(default=False, verbose_name='is featured')),
                ('total_orders', models.PositiveIntegerField(default=0, verbose_name='total orders')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3, verbose_name='average rating')),
                ('total_reviews', models.PositiveIntegerField(default=0, verbose_name='total reviews')),
                ('tags', models.CharField(blank=True, help_text='Comma-separated tags', max_length=500, verbose_name='tags')),
                ('meta_description', models.CharField(blank=True, max_length=160, verbose_name='meta description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='skills.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Skill',
                'verbose_name_plural': 'Skills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillFAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300, verbose_name='question')),
                ('question_ar', models.CharField(blank=True, max_length=300, verbose_name='question (Arabic)')),
                ('answer', models.TextField(verbose_name='answer')),
                ('answer_ar', models.TextField(blank=True, verbose_name='answer (Arabic)')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Skill FAQ',
                'verbose_name_plural': 'Skill FAQs',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='SkillImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='skills/images/', verbose_name='image')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='caption')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='order')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='skills.skill')),
            ],
            options={
                'verbose_name': 'Skill Image',
                'verbose_name_plural': 'Skill Images',
                'ordering': ['order', 'created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['category', 'status'], name='skills_skil_categor_6a7dcb_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['points_required'], name='skills_skil_points__e327ee_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['average_rating'], name='skills_skil_average_44c71e_idx'),
        ),
        migrations.AddIndex(
            model_name='skill',
            index=models.Index(fields=['created_at'], name='skills_skil_created_e70221_idx'),
        ),
    ]
